apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: businesslogic
  labels:
    app: businesslogic
spec:
  selector:
    matchLabels:
      app: businesslogic
  replicas: 1
  template:
    metadata:
      labels:
        app: businesslogic
    spec:
      containers:
      - name: master
        image: demo-internal:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  selector:
    matchLabels:
      app: frontend-service
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: master
        image: demo-external:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
